# Generated by Django 4.2.4 on 2023-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=15)),
                ('project_description', models.CharField(max_length=50)),
                ('project_lead', models.CharField(max_length=50)),
                ('team_size', models.CharField(max_length=50)),
                ('programming_language', models.CharField(max_length=50)),
                ('project_start_date', models.DateField()),
                ('project_delivery_date', models.DateField()),
            ],
        ),
    ]
